runtime: python310

env_variables:
  SECRET_KEY: "dev"
  FLASK_ENV: "development"
  FLASK_APP: "src"
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@35.198.19.103/gemini"
  SQLALCHEMY_DATABASE_URI_ASNC: "postgresql+asyncpg://postgres:postgres@35.198.19.103/gemini"
  JWT_SECRET_KEY: "JWT_SECRET_KEY"

service: gemini-flask-services

network:
  name: projects/gemini-382419/global/networks/default
  subnetwork_name: projects/gemini-382419/regions/southamerica-east1/subnetworks/default