runtime: python310

env_variables:
  SECRET_KEY: "dev"
  FLASK_ENV: "development"
  FLASK_APP: "src"
  SQLALCHEMY_DATABASE_URI: "postgresql://postgres:postgres@34.95.195.135/tcc"
  SQLALCHEMY_DATABASE_URI_ASNC: "postgresql+asyncpg://postgres:postgres@34.95.195.135/tcc"
  JWT_SECRET_KEY: "JWT_SECRET_KEY"

service: tcc-flask-services

network:
  name: projects/tccmba/global/networks/default
  subnetwork_name: projects/tccmba/regions/southamerica-east1/subnetworks/default