steps:
# Compilação do container
- name: 'gcr.io/tccmba/docker'
  args: ['build', '-t', 'gcr.io/tccmba/gcloud', '.']

# # Run database migrations

#push
- name: 'gcr.io/tccmba/docker'
  args: ['push', 'gcr.io/tccmba/gcloud']

# # Testes

# Implantação no Cloud Run
- name: 'gcr.io/tccmba/gcloud'
  args:
    - 'run'
    - 'deploy'
    - 'tcc-backend-services'
    - '--image=gcr.io/tccmba/gcloud'
    - '--platform=managed'
    - '--region=southamerica-east1'
    - '--allow-unauthenticated'
    - '--memory=2Gi'
    - '--set-env-vars=FLASK_ENV=development,SECRET_KEY=prod,SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@34.95.195.135:5432/tcc,SQLALCHEMY_DATABASE_URI_ASNC=postgresql+asyncpg://postgres:postgres@34.95.195.135:5432/tcc,TEST_DATABASE_URI=sqlite:///test.db,FLASK_DEBUG=1'
timeout: 1800s